name: cobi_flutter_share
description: A plugin that offers usage for incoming shares
version: 4.0.0
homepage: https://github.com/Cobinja/cobi-flutter-share/tree/main/cobi_flutter_share

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cobi_flutter_share_platform_interface: ^4.0.0
  cobi_flutter_share_android: ^4.0.0
  json_annotation: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cobi_flutter_share_android
