name: cobi_flutter_share
description: A plugin that offers usage for incoming shares
version: 2.1.0
homepage: https://github.com/Cobinja/cobi-flutter-share/tree/main/cobi_flutter_share

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cobi_flutter_share_platform_interface: ^2.1.0
  cobi_flutter_share_android: ^2.1.0
  json_annotation: ^4.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cobi_flutter_share_android
